### ISSUE TITLE
Cannot install root-framework from snap

### ISSUE THREAD

**Issue by edmondium** [MrCarroll/root-snap#2] opened 2022-09-11 09:23 UTC

**Comment by MrCarroll** [comment] 2022-09-11 12:10
Hello,

Could you please provide the terminal output of the following commands:

`uname -a`
`snap version`
`sudo snap install root-framework`

**Comment by edmondium** [comment] 2022-09-11 14:29
edmondium@LAPTOP-1Q9H40K6:~$ uname -a
Linux LAPTOP-1Q9H40K6 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

edmondium@LAPTOP-1Q9H40K6:~$ sudo daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target

edmondium@LAPTOP-1Q9H40K6:~$ pidof systemd
11

edmondium@LAPTOP-1Q9H40K6:~$ exec sudo nsenter -t $(pidof systemd) -m -p su - $LOGNAME

edmondium@LAPTOP-1Q9H40K6:~$ snap version
snap    2.56.2+22.04ubuntu1
snapd   2.56.2+22.04ubuntu1
series  16
ubuntu  22.04
kernel  5.10.102.1-microsoft-standard-WSL2

edmondium@LAPTOP-1Q9H40K6:~$ sudo snap install root-framework
[sudo] password for edmondium:
error: cannot perform the following tasks:
- Setup snap "root-framework" (723) security profiles for auto-connections (cannot obtain mount security snippets for snap "root-framework": shared-memory plug with "private: true" cannot be connected if "/dev/shm" is a symlink)

**Comment by MrCarroll** [comment] 2022-09-11 17:03
Snaps aren't ideal for running in WSL2, there is some ongoing long term work that might make them better supported in the future, but you may find it preferable to mak use of the ROOT pre-compiled binary distrbutions ( https://root.cern/install/#download-a-pre-compiled-binary-distribution ) or the Conda package ( https://root.cern/install/#conda ) which would act exactly how they otherwise would in a traditional Ubuntu environment.

If you did want to proceed with the ROOT snap anyway, the bug is caused by WSL2's setup of the `/dev/shm` folder. As an naive fix. you can `sudo rm /dev/shm` and then `sudo mkdir /dev/shm && sudo chmod 777 /dev/shm`. The install command would then work as you expect.

It would be preferable however to add `/dev/shm` to `/etc/fstab`, setup as a `tmpfs`, so that it acts as it's supposed to as a place to store memory backed files; and also would properly clear itself up, which you might be able to do by adding a line to `/etc/fstab` such as:

`tmpfs           /dev/shm            tmpfs   rw,mode=1777,size=1g`

Ideally after rebooting the system (Windows, or Linux via the `wsl.exe --terminate` command), this would take effect and the ROOT snap would also install.

**Comment by MrCarroll** [comment] 2022-10-04 18:18
As an update to this, Microsoft/Canonical have announced official support for systemd in the past week or so; and when enabled, the ROOT snap installs fine with no extra configuration required.

https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

As there's now an approved way of enabling snaps in WSL2, and the issue here doesn't exist when you do so via this method, I'll close this issue for now.

**Closed by MrCarroll** 2022-10-04 18:18 UTC
